### ISSUE TITLE
emergency=lifeguard

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-tagging#1]
I was looking at [Key:emergency](https://wiki.openstreetmap.org/wiki/Key:emergency) 
We have too many tags for different kinds of lifeguards.  This is too confusing. I don’t want to have to show all these choices to iD users.

Let's use `emergency=lifeguard` as the main key for "a lifeguard is here" and use subtag `lifeguard=*` for the details about what the lifeguard stand looks like.

### Related

* iD ticket https://github.com/openstreetmap/iD/issues/4918

### Next Actions

* [X] Notify tagging list: [discussion thread link](https://lists.openstreetmap.org/pipermail/tagging/2018-June/037080.html
)
* [ ] Update OSM Wiki
* [ ] Propose mechanical edit to change the existing tags
* [ ] Carry out that mechanical edit
* [x] Update iD preset:  https://github.com/openstreetmap/iD/issues/4918

**Comment by andrewharvey** [comment]
Why not just add a new emergency=lifeguard for a generic, and leave in place the existing tags? Thinking about this more, if we do it that way, then you get the simpler option in iD without affecting already accepted tagging practices, existing data consumers and existing mapped features.

That seems much easier and preferable than doing items 2,3,4.

**Comment by bhousel** [comment]
> Why not just add a new emergency=lifeguard for a generic, and leave in place the existing tags? Thinking about this more, if we do it that way, then you get the simpler option in iD without affecting already accepted tagging practices, existing data consumers and existing mapped features.
> 
> That seems much easier and preferable than doing items 2,3,4.

In most cases I would agree, but we're talking about a tag that is used only a few hundred times. (yes I picked an easy one on purpose for issue #1)

It would take someone an hour or two to change the tag to something else.  The "mechanical edit" can simply be "open them all up in level0 and change them".

I can't imagine that there are any data consumers.  What kind of a map has 24 lifeguard_platforms on it?   

(We are doing this now before the tag becomes a bigger problem later and people have mapped 2000 of them)

**Comment by bhousel** [comment]
> Why not just add a new emergency=lifeguard for a generic, and leave in place the existing tags? Thinking about this more, if we do it that way, then you get the simpler option in iD without affecting already accepted tagging practices, existing data consumers and existing mapped features.

☝️  I'm just going to do this .. It's the simplest thing
